### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [medyagh/gopogh#38]
hi @medyagh, first of all thanks for this work, it helps to make the output of the tests clear! 

I wanted to check the documentation and found that it's not shown in https://pkg.go.dev/github.com/medyagh/gopogh@v0.13.0/pkg/report because there is not any license. Would you mind adding a license to allow us to use it? 

Thanks!

**Comment by medyagh** [comment]
thank you that has been on my radar to add the right license for this project, will get back to you soon

**Comment by mauriciovasquezbernal** [comment]
Great, thanks @medyagh!
